manifest:
  version: "0.13"

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: beriberikix
      url-base: https://github.com/beriberikix

  projects:
    - name: zephyr
      remote: zephyrproject
      revision: main
      import:
        name-allowlist: []

    - name: zephyrdb
      remote: beriberikix
      revision: main
      path: modules/lib/zephyrdb

  self:
    path: zephyrdb-example
